### ISSUE TITLE
HTTPResponse' object has no attribute 'read_chunked'

### ISSUE THREAD

**Issue by tripledes** [kubevirt/ansible-kubevirt-modules#222] opened 2019-04-23 09:54 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Using:

```yaml
---
- hosts: localhost
  tasks:
    - name: Deploy CentOS 7 VM
      kubevirt_vm:
          state: running
          wait: true
          name: centosvm
          namespace: default
          memory: 1024M
          cloud_init_nocloud:
            userData: |-
              #cloud-config
              password: cloud
              chpasswd: { expire: False }
          disks:
            - name: containerdisk
              volume:
                persistentVolumeClaim:
                  claimName: pvc0090
              disk:
                bus: virtio
```

The VM/I were created but Ansible returned error:

```shell
[sup@sjr2 playbooks]$ ansible-playbook centos_vm.yml
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Deploy CentOS 7 VM] ************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'HTTPResponse' object has no attribute 'read_chunked'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "'HTTPResponse' object has no attribute 'read_chunked'"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**What you expected to happen**:

Ansible to report changed = 1

**How to reproduce it (as minimally and precisely as possible)**:

Try to apply the above playbook

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.16.0
- Kubernetes version (use `kubectl version`): 1.12.4 (OCP4 Libvirt VMs)
- VM or VMI specifications:
- Cloud provider or hardware configuration: HW
- OS (e.g. from /etc/os-release): RHEL7
- Kernel (e.g. `uname -a`): 3.10
- Install tools: ansible 2.8.0b1
- Others:

**Comment by mmazur** [comment] 2019-04-23 10:04
1. Please verify all your libs in pip are up to date (`openshift` in particular).
2. If you could attach the full stack trace of the issue when running `ansible-playbook -vvv`

(For reference: https://github.com/openshift/openshift-restclient-python/issues/273 though this should not happen in our current code.)

**Comment by tripledes** [comment] 2019-04-23 10:49
> 1. Please verify all your libs in pip are up to date (`openshift` in particular).

I'm not using pip but rather the ansible (downstream) rpm version 2.8.0b.

> 2. If you could attach the full stack trace of the issue when running `ansible-playbook -vvv`
> 

```shell
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_kubevirt_vm_payload_O18yxd/__main__.py", line 413, in main
    module.execute_module()
  File "/tmp/ansible_kubevirt_vm_payload_O18yxd/__main__.py", line 397, in execute_module
    patched, k8s_obj = self.manage_vm_state(our_state, crud_executed)
  File "/tmp/ansible_kubevirt_vm_payload_O18yxd/__main__.py", line 316, in manage_vm_state
    k8s_obj = self._wait_for_vm_state(new_state)
  File "/tmp/ansible_kubevirt_vm_payload_O18yxd/__main__.py", line 282, in _wait_for_vm_state
    for event in self._kind_resource.watch(namespace=self.namespace, timeout=self.params.get('wait_timeout')):
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 312, in watch
    timeout_seconds=timeout
  File "/usr/lib/python2.7/site-packages/kubernetes/watch/watch.py", line 134, in stream
    for line in iter_resp_lines(resp):
  File "/usr/lib/python2.7/site-packages/kubernetes/watch/watch.py", line 47, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
AttributeError: 'HTTPResponse' object has no attribute 'read_chunked'
```

> (For reference: [openshift/openshift-restclient-python#273](https://github.com/openshift/openshift-restclient-python/issues/273) though this should not happen in our current code.)

**Comment by mmazur** [comment] 2019-04-23 11:09
Ok, based on that backtrace it does indeed seem like the python libs are rpm–sourced. In that case, please provide the output of `rpm -qf /usr/lib/python2.7/site-packages/openshift/dynamic/client.py /usr/lib/python2.7/site-packages/kubernetes/watch/watch.py`

**Comment by tripledes** [comment] 2019-04-23 11:42
> Ok, based on that backtrace it does indeed seem like the python libs are rpm–sourced. In that case, please provide the output of `rpm -qf /usr/lib/python2.7/site-packages/openshift/dynamic/client.py /usr/lib/python2.7/site-packages/kubernetes/watch/watch.py`

python2-openshift-0.8.6-1.el7.noarch
python2-kubernetes-8.0.1-1.el7.noarch

**Comment by mmazur** [comment] 2019-04-23 13:18
Ok, I'll see what we can figure out as to the causes.

**Comment by ccamacho** [comment] 2019-06-29 03:50
Hey folks, I had the same issue and the only way to fix it from my side was by: 
https://github.com/kubernetes-client/python-base/pull/140
@mmazur @tripledes 

Reported here: https://github.com/kubernetes-client/python-base/issues/139

**Comment by mmazur** [comment] 2019-09-27 08:20
Closing. If we hit it again, we can reopen. Maybe someone fixed it somewhere else in the code… 🤞

**Closed by mmazur** 2019-09-27 08:20 UTC
Labels: kind/bug
